baseURL = 'kristian_site/'
languageCode = 'en-us'
title = 'Kristian De Leon'

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "Bio"
    name = "Bio"
    url = "/bio/"
    weight = 11
  [[menu.main]]
    identifier = "works"
    name = "Works"
    url = "/works/"
    weight = 12
  [[menu.main]]
    identifier = "videos"
    name = "Videos"
    url = "/videos/"
    weight = 13
