baseURL = '/'
languageCode = 'en-us'
title = 'KRISTIAN DE LEON'
theme = 'holy'

[markup.goldmark.renderer]
  unsafe = true

[params]
  copyright = "kdeleonmusic@gmail.com"

[menu]
  [[menu.main]]
    identifier = "home"
    url = "/home/"
    weight = 10
  [[menu.main]]
    identifier = "Bio"
    name = "Bio"
    url = "/bio/"
    weight = 11
  [[menu.main]]
    identifier = "works"
    name = "Works"
    url = "/works/"
    weight = 12
  [[menu.main]]
    identifier = "videos"
    name = "Videos"
    url = "/videos/"
    weight = 13
